name: "Install Flutter Dependencies"

description: "dependencies install step"

runs:
  using: "composite"
  steps:
    - name: "Read flutter version from fvm config"
      id: flutter_info
      run: |
        FLUTTER_VERSION=$(jq -r '.flutterSdkVersion' ./.fvm/fvm_config.json)
        echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: "Setup Flutter"
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: "Install melos"
      run: |
        dart pub global activate melos
        sed -i '/sdkPath/d' melos.yaml
      shell: bash
      env:
        MELOS_SDK_PATH: ${{ steps.flutter-action.outputs.CACHE-PATH }}
