name: tokeru

packages:
  - packages/**

scripts:
  gen:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: "build_runner"
    exec:
      concurrency: 1

sdkPath: .fvm/flutter_sdk
