name: quick_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.13 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: 2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.2.1
  riverpod_generator: ^2.3.11
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_markdown: ^0.6.18
  collection: ^1.17.0
  intl: ^0.18.1
  desktop_window: ^0.4.0
  super_hot_key: ^0.8.5
  logger: ^2.0.2+1
  # firebase
  firebase_auth: ^4.17.4
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.4.13
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.6

  url_launcher: ^6.2.5

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
