name: tokeru_desktop
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Riverpod
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  riverpod_generator: ^3.0.0-dev.11
  flutter_hooks: ^0.20.5

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.17.0
  intl:
  logger: ^2.0.2+1
  uuid: ^4.4.0

  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

  hotkey_manager: ^0.2.2

  # firebase & google
  # TODO: descktopからは削除して、modelに移動する
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_crashlytics: ^4.0.4
  cloud_firestore: ^5.2.1
  firebase_analytics: ^11.2.1

  url_launcher: ^6.2.5

  # melos
  tokeru_widgets:
  tokeru_model:
  tokeru_haptics:

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  generate: true
