name: tokeru_widgets
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: 2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.2.1
  riverpod_generator: ^2.3.11
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  flutter_linkify: ^6.0.0
  shared_preferences: ^2.2.3
  intl: ^0.18.0

  # firebase
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.4
  firebase_analytics: ^10.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.5
