name: bump-app-version

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  analyze:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Java environment
        uses: actions/setup-java@v3.11.0
        with:
          distribution: "zulu"
          java-version: "12.x"

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Get current date and time
        id: timestamp
        run: |
          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create new feature branch
        run: |
          git checkout -b feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }}

      - name: Install cider
        run: flutter pub global activate cider

      - name: Increment patch version
        run: flutter pub global run cider bump patch

      - name: Commit and Push to new feature branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@github.com"
          git add pubspec.yaml
          git commit -m "Update pubspec.yaml"
          git push origin feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }}

      - name: create Pull Request to flutter-repo
        run: |
          gh pr create \
            --title "update pubspec version" \
            --repo snkrdunk/snkrdunk_flutter \
            --body "This PR incrementally updates pubspec version" \
            --base develop \
            --head feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }} \
            --reviewer daisukeueta,hitotsu01ki,imajoriri,hsylife
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
