name: Build and Release macOS App

# TODO: workflow_dispatchに変更する
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "setup java"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Install codemagic-cli-tools"
        run: |
          pip3 install codemagic-cli-tools

      - name: "codemagic cli tools version"
        run: |
          codemagic-cli-tools --version

      - name: "Install the Apple certificate"
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          openssl pkcs12 -in $CERTIFICATE_PATH -nodes -nocerts -password pass:$P12_PASSWORD | openssl rsa -out $RUNNER_TEMP/cert_key

      - name: "Install the Apple provisioning profile(Codesigning)"
        run: |
          app-store-connect fetch-signing-files com.tokeru.macos.prod \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --certificate-key=@file:$RUNNER_TEMP/cert_key \

      - name: "Install the Apple provisioning profile(Distribution)"
        run: |
          app-store-connect fetch-signing-files com.tokeru.macos.prod \
            --type MAC_INSTALLER_DISTRIBUTION \
            --certificate-key=@file:$RUNNER_TEMP/cert_key \
            --save

      # - name: Build macOS app
      #   run: flutter build macos --dart-define-from-file=dart_defines/prod.json

      # - name: Zip the app
      #   run: |
      #     cp -r build/macos/Build/Products/Release/Tokeru.app Tokeru.app
      #     zip -r release.zip Tokeru.app

      # - name: Upload ZIP to Release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: ./release.zip
      #     asset_name: app-macos.zip
      #     asset_content_type: application/zip
