name: Build and Release macOS App

# TODO: workflow_dispatchに変更する
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "setup java"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Install codemagic-cli-tools"
        run: |
          pip3 install codemagic-cli-tools

      - name: "codemagic cli tools version"
        run: |
          codemagic-cli-tools --version

      # - name: Build macOS app
      #   run: flutter build macos --dart-define-from-file=dart_defines/prod.json

      # - name: Zip the app
      #   run: |
      #     cp -r build/macos/Build/Products/Release/Tokeru.app Tokeru.app
      #     zip -r release.zip Tokeru.app

      # - name: Upload ZIP to Release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: ./release.zip
      #     asset_name: app-macos.zip
      #     asset_content_type: application/zip
