name: flutter test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Run tests"
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage/lcov.info
