name: flutter test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Run tests"
        run: melos exec -- "flutter test"
        env:
          MELOS_SDK_PATH: ${{ FLUTTER_ROOT }}
