name: flutter analyze

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Run analyze"
        run: melos analyze --sdk-path ${{ steps.flutter-action.outputs.CACHE-PATH }}
