name: flutter test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Read flutter version from fvm config"
        id: flutter_info
        run: |
          FLUTTER_VERSION=$(jq -r '.flutterSdkVersion' ./path/to/flutter_version.json)
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: stable
          cache: true
      - name: "Run tests"
        run: flutter test
