name: Create goldten test pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Run tests"
        run: flutter test --update-goldens

      - name: Get current date and time
        id: timestamp
        run: |
          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Commit and Push to new feature branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@github.com"
          git checkout -b feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }}
          git add .
          git commit -m "Update pubspec.yaml"
          git push origin feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }}

      - name: create Pull Request to flutter-repo
        run: |
          gh pr create \
            --title "update goldten test" \
            --repo imajoriri/tokeru \
            --body "update goldten test" \
            --base main \
            --head feature/update-pubspec-${{ steps.timestamp.outputs.timestamp }} \
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
