name: Create golden test pull request

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install_flutter_dependencies

      - name: Config git
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@github.com"

      # 現在のブランチと作成するブランチの名前をセットする
      - name: Set branch name
        run: |
          echo "current_branch=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "new_branch=${{ github.head_ref }}-update-golden" >> $GITHUB_ENV

      - name: Check new branch exists
        run: |
          git ls-remote --heads origin $new_branch
          if git ls-remote --heads origin $new_branch | grep -q "refs/heads/$new_branch"; then
            echo "new_branch_exist=true" >> $GITHUB_ENV
          else
            echo "new_branch_exist=false" >> $GITHUB_ENV
          fi

      # ブランチの作成。
      # すでにリモートにブランチが存在する場合はそのブランチに切り替える。
      # ブランチが存在しない場合は新規作成する。
      - name: Create new branch
        run: |
          if $new_branch_exist = "true"; then
            git fetch origin $new_branch
            git fetch origin $current_branch
            git branch $new_branch origin/$new_branch
            git checkout $new_branch
            git merge origin/$current_branch
          else
            git checkout -b $new_branch
          fi

      # Goldenファイルの更新をし、変更があるかどうかを確認する
      - name: Update golden file and check changes
        run: |
          flutter test --update-goldens
          git status --porcelain
          if ! git status --porcelain | grep -q ".*\/goldens\/.*\.png"; then
            echo "Error: No golden test changes found."
            exit 1
          fi

      - name: Git add, commit and push
        run: |
          git add .
          git commit -m "Update golden test"
          if $new_branch_exist = "true"; then
            git push
          else
            git push origin $new_branch
          fi

      # PRが存在しない場合のみPRを作成する
      - name: Create pull request if not exists
        run: |
          PR_COUNT=$(gh pr list --head $new_branch --json number --jq length)
          if [ "$PR_COUNT" -eq 0 ]; then
            gh pr create \
              --title "update goldten test" \
              --repo ${{ github.repository }} \
              --body "update goldten test" \
              --base $current_branch \
              --head $new_branch
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
