name: Build and Release macOS App

# on:
#   release:
#     types: [published]
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.event.release.target_commitish }}
          ref: main

      - uses: ./.github/actions/install_flutter_dependencies

      - name: "Build macOS app"
        run: flutter build macos --dart-define-from-file=dart_defines/prod.json

      - name: "npm install -g appdmg"
        run: npm install -g appdmg

      - name: "Create DMG"
        run: appdmg config.json ./test.dmg
